### ISSUE TITLE
No icon in logseq's marketplace

### ISSUE THREAD

**Issue by ituri** [rcvd/logseq-things-theme#3]
cf. title: The link to the theme's icon appears to be broken.

**Comment by xyhp915** [comment]
The missing icon was added #2 But may need to republish a new version. cc @rcvd

**Comment by rcvd** [comment]
I can see it when loading the marketplace:
 
<img width="1269" alt="Screenshot 2022-01-04 at 07 06 21" src="https://user-images.githubusercontent.com/12938875/148016491-76d8473a-8b10-4bfc-b5b7-43b10fb5842d.png">

**Comment by rcvd** [comment]
It's broken once you downloaded the theme...haven't seen this:

<img width="407" alt="Screenshot 2022-01-04 at 07 10 33" src="https://user-images.githubusercontent.com/12938875/148016795-646281d6-4422-4cf4-9d6b-ba06e1e78e75.png">

**Comment by xyhp915** [comment]
It works now for me :)
![1F55EA70-AB36-4A34-AFD0-D30BD145293C](https://user-images.githubusercontent.com/1779837/148022688-bb815810-cca9-4712-96d2-41d99602737a.png)
